#+title: To be implemented

* TODO Refactor: move package functionality to org-chronos.el
There is code hanging around that should be in org-chronos.
For example:

(defgroup org-chronos nil
  "Event-sourced time tracking for Org-mode."
  :group 'org
  :prefix "chronos-")

(defcustom chronos-log-directory (expand-file-name "chronos-logs" user-emacs-directory)
  "Directory for storing chronos event logs."
  :type 'directory
  :group 'org-chronos)

(defconst chronos-event-priorities
  '(:day-start 0 :stop 10 :interruption 20 :ctx-switch 30 :tick 40)
  "Event type priorities for sorting.")

#+end_src
* TODO Feature: ask for time when starting the day
When executing the command to start the day, ask for the time that it should be started at, defaulting to the current time and allowing both an absolute time (HH:MM)
or a relative time (-20) (indicating 20 minutes ago)

* TODO Feature: keep all actions, even when deactivated
Since actions change dynamically, things move vertically
when the buffer window is narrow (because of line breaks).
In order to avoid that, one possibility is to just keep all
the actions always visible, but to activate and deactivate them
as needed. When deactivated, it should be clearly visible (for
example, by making the font gray / shaded)

* DONE Feature: break implementation in separate files
For development convenience, clarity and to keep files short
break down the implementation of org-chronos in different files.
On possible idea:
- org-chronos-interfaces.el
  All the interfaces (and perhaps the data structures the interfaces use)
- org-chronos-persistence.el Code related to persistence (default implementation of the
  persistence interface + any other alternative implementation that
  might already exist, auxiliary functions, ...)
- org-chronos-event-log.el
  Idem, for the corresponding interface
- org-chronos-app-state.el
  Idem, for the corresponding interface
- org-chronos-renderer.el
  Idem, for the corresponding interface
- org-chronos-ui.el
  UI of the application, event handlers, evil-mode, etc.
- org-chronos.el
  Package mode like defgroup declarations, set-up of the IoC
  container, setting any global variable, etc.

Remember to updade the dev-load.el file and to create different test files for different files (for those that need to have tests,
which excludes the org-chronos-interfaces.el and org-chronos.el
files, at least)
